### PR TITLE
Pressure,Temperature and Altitude - minimal code to log bmp280

### PR DESCRIPTION
**Pull request by jygh98**

### CODE REVIEW

**Comment by carlosparadis** [comment]
@jygh98 I am not sure this is correct. I already have your first commit to the pressure, temp and altitude in the repo. Shouldn't you just need to send the "corrected name of sensor"? What is the intent of the first commit?

**Comment by jygh98** [comment]
so i rechecked issue 16 and i only pushed the commit to my fork, so i still needed to make a PR was so that it included the original commit and the renaming commit.

**Comment by jygh98** [comment]
Regarding the last commit, when i tried to retest the sensors i forgot that i commented out the altitude reading in #f11a295.  Then when i uncommented it, i noticed that i was getting a negative value for altitude and figured i needed to calibrate the altitude reading with the sealevel pressure.

**Comment by carlosparadis** [comment]
@jygh98 Can you ask @ryantanaka to help you squash this into fewer commits? There is now too much back and forth in confusion: File name, accidental comment, unseen error due to unseen comment, etc! :( 

Also, what is a "shebang" on this commit message? :|

**Comment by carlosparadis** [comment]
@jygh98 Just realized this was the extra sensor. Focus on the things we need to wrap up before you leave and leave this one as last in case you don't have time.

**Comment by carlosparadis** [comment]
I see you did the squash, so I will go ahead and merge this. Thanks!

**Pull request merged**
