### PR TITLE
Convert egauge script text storage to database REVISION 2

### PR DESCRIPTION
**Pull request by matthew-schultz**
continuation of this pull request: https://github.com/erdl/sensors/pull/52

### CODE REVIEW

**Comment by carlosparadis** [comment]
ok great, let me know when you are done with the revisions with the main and I will take a full pass.

**Comment by matthew-schultz** [comment]
oh, this pull request already includes the revisions to main

shoot, maybe I shouldn't have squashed those revisions...

**Comment by matthew-schultz** [comment]
Ah, that's right; I'll need to refactor my unit tests for the changes to get_data_from_api(), but I should be able to do that.

I don't understand what you mean about not being able to see only two levels of abstraction of functions.

Are you talking about how functions called by the main block cannot call other functions in api_egauge.py?

**Comment by carlosparadis** [comment]
> Are you talking about how functions called by the main block cannot call other functions in api_egauge.py?

@matthew-schultz Yup. We agreed unless they needed to be reused everywhere we wouldn't try to add any more for now, and defer them to later after everything was functional to decide how to go about putting them in other files.

**Comment by matthew-schultz** [comment]
Do you have any examples of how I'm not doing that? I thought I was already using functions that way in api_egauge for this PR

**Comment by carlosparadis** [comment]
Copy and paste the code of the function in the body for now and leave a comment on it. As I said before, we want to keep the inside of each function without more calls so we decide later on the overlap across all projects. It's too early to modularize beyond the functions on main. 

Feel free to indicate what you want as a function in the body on a comment. Once we have the things running we can elect of all the candidates what makes the most sense to separate into different modules.

**Comment by matthew-schultz** [comment]
As far as I can tell, I have not modularized beyond any functions in main in this PR

If you see functions calling functions they are probably calls to external modules (sqlalchemy, arrow, etc) and if you would like me to clarify something, let me know.

https://github.com/erdl/sensors/blob/fd075d86964e9bd13f7a41581266fbe17a87b6ed/egauge/script/api_egauge.py#L31-L37

https://github.com/erdl/sensors/blob/fd075d86964e9bd13f7a41581266fbe17a87b6ed/egauge/script/api_egauge.py#L40-L50

https://github.com/erdl/sensors/blob/fd075d86964e9bd13f7a41581266fbe17a87b6ed/egauge/script/api_egauge.py#L53-L85

https://github.com/erdl/sensors/blob/fd075d86964e9bd13f7a41581266fbe17a87b6ed/egauge/script/api_egauge.py#L88-L117

https://github.com/erdl/sensors/blob/fd075d86964e9bd13f7a41581266fbe17a87b6ed/egauge/script/api_egauge.py#L120-L126

https://github.com/erdl/sensors/blob/fd075d86964e9bd13f7a41581266fbe17a87b6ed/egauge/script/api_egauge.py#L129-L136

**Comment by carlosparadis** [comment]
I missed it on the main, but the function of concern is this one:

https://github.com/erdl/sensors/blob/fd075d86964e9bd13f7a41581266fbe17a87b6ed/egauge/script/api_egauge.py#L43

**Comment by matthew-schultz** [comment]
Yeah, I think remember some discussion about that.

I'll move the code for __get_most_recent_timestamp_from_db()__ into __get_data_from_api()__ so main should look something like this:
```python3
if __name__ == "__main__":
    sensor_id = 'egauge31871'
    unit_of_time = 'm'
    conn = get_db_handler()
    try:
        readings = get_data_from_api(conn, sensor_id, unit_of_time)
    except (requests.exceptions.ConnectionError, Exception) as e:
        log_failure_to_connect_to_api(conn)
        sys.exit()
    try:
        insert_readings_into_database(conn, readings, sensor_id)
    except Exception as e:
        log_failure_to_connect_to_database(conn)
        sys.exit()
```

**Comment by carlosparadis** [comment]
When you do that, dissolve the function and leave a comment that was a function before so we can reconsider later how and if we will need it.

**Comment by matthew-schultz** [comment]
Before I force push changing get_data_from_api() and dissolving get_most_recent_timestamp_from_db() I just want to make sure:

We wouldn't ever want to run get_data_from_api() with custom times instead of the latest_read_timestamp and/or the current time, right? (e.g. if there's a hole in the readings data over a certain time period, or if we want to test retrieving readings data over a certain time)

Ideally there wouldn't ever be holes in the data, but if there was, I could keep the current arguments for get_data_from_api() and get_most_recent_timestamp_from_db() and in the future add flags to run the script over a custom time.

**Comment by carlosparadis** [comment]
@matthew-schultz Yes we will, but I don't intend to use the code you are using right now for that intent. Instead, we will create a separate file, which also has a main, which may in turn rely on the functions you coded for that main. Afterall, the intent is different, the main should be different. Multiple "wonky" reuses of the same code leads to confusion when troubleshooting. 

For instance, if I am running this manually, the timestamps of when things were running normally via cron job versus when someone manually run would be the same. I'd rather they be not. 

So, for now, disregard manual runs, and focus on the cron job and add this for a "following feature" in the issue with all the wish list.

**Comment by matthew-schultz** [comment]
@carlosparadis I've pushed the requested updates

**Comment by carlosparadis** [comment]
After all the revisions, does it run? What should I expect to see in the database again worth of logs?

**Comment by matthew-schultz** [comment]
Yeah, I've tested running the latest version of api_egauge.py (along with the unit tests) from the terminal on my machine and it works.

---

###  __database_insertion_timestamp__ INSERTION BEHAVIOR for api_egauge.py

if __get_data_from_api()__ runs and but no timestamp is retrieved from database_insertion_timestamp:
- nothing is inserted into  __database_insertion_timestamp__ 
- exit()

if __get_data_from_api()__ runs successfully:

timestamp | is_success
--- | ---
2018-09-11 01:00:00 |

if an __error__ is caught or __insert_readings_into_database()__ runs successfully and inserts __no rows__ of readings:

timestamp | is_success
--- | ---
2018-09-11 01:00:00 | False


if __insert_readings_into_database()__ runs successfully and inserts __at least one row__ of readings:

timestamp | is_success
--- | ---
2018-09-11 01:00:00 | True

---

database_insertion_timestamp logging functionality:
- get_data_from_api() inserts a new row into database_insertion_timestamp on success, with no value for is_success (Since I only insert is_success=True after readings are successfully inserted)
- insert_readings_into_database() inserts a new row into database_insertion_timestamp after it finishes running. It sets is_success to True if at least one reading was inserted or False if no readings were inserted.
- log_failure_to_connect_to_api() and log_failure_to_connect_to_database() insert a new row into database_insertion_timestamp with is_success=False if their associated exception blocks trigger, respectively. DEVELOPMENT FEATURE THAT MAY BE REMOVED: Log error time and stack trace to text file 'error.log'.

**Comment by carlosparadis** [comment]
What about the table names? Are we keep them in two separate tables now or the same?

I have a trip this week, so I won't have time to review in detail. I suggest you go ahead and code the webctrl similar to what we did in this PR and open a separate PR on it on the meantime.

**Comment by matthew-schultz** [comment]
Ahh, I hope your trip goes well!

> Are we keep them in two separate tables now or the same?

I think you're asking if I have separate tables for the get_data_from_api() timestamps and insert_readings_into_database() timestamps?

They both are in the same table __database_insertion_timestamp__.

__We want just one table for logging status timestamps at this point right?__

>  I suggest you go ahead and code the webctrl similar to what we did in this PR and open a separate PR on it on the meantime.

Sounds good, I'll go ahead and continue working on webctrl, unless we need to make any more changes to egauge.

**Comment by matthew-schultz** [comment]
Pushed updates to sensor_info table mentioned https://github.com/erdl/sensors/issues/62#issuecomment-471141348

**Comment by matthew-schultz** [comment]
5/16 meeting

Make sure that insert data into readings and update sensor_info timestamp are in the same transaction and that they cannot be separately updated by accident

**Comment by carlosparadis** [comment]
I noted a few comments down, but after taking a full pass, they seem overall minor and can be addressed later. It is also getting a bit confusing for me to make sense of all the commits since they are very large changes, so I will defer the small notes to a separate issue. Good job!

**Pull request merged**
