### PR TITLE
Create hobo script

### PR DESCRIPTION
**Pull request by matthew-schultz**

### CODE REVIEW

**Comment by carlosparadis** [comment]
That's great. Don't PR the other 3 classes until I get a chance to accept the non-class version into the codebase so we can get the 2 versions apart in the version control. Remember if you commit to your own repo in the same branch, the PR will automatically update here. Otherwise, you're free to continue them in a separate branch.

**Comment by matthew-schultz** [comment]
Pushed updates to sensor_info table and usage of its fields mentioned here https://github.com/erdl/sensors/issues/62#issuecomment-471141348 and here https://github.com/erdl/sensors/issues/60#issuecomment-471143350

Note: pushed to matthew-schultz/sensors branch 60-hobo a second time today to properly rebase onto erdl/sensors master branch. # of files changed in this this PR should now correctly read "2" instead of "6"

**Comment by matthew-schultz** [comment]
5/16 meeting

Make sure that insert data into readings and update sensor_info timestamp are in the same transaction and that they cannot be separately updated by accident

**Comment by carlosparadis** [comment]
Since I don't see any major issues here, and mostly are refactoring, I will go ahead and accept the PR. Let's moved the pending concerns to issues in smaller scope to keep things more organized. Good job!

**Pull request merged**
