### PR TITLE
add timestamps to egauge api and build unit test class

### PR DESCRIPTION
**Pull request by matthew-schultz**
@carlosparadis

### CODE REVIEW

**Comment by carlosparadis** [comment]
@matthew-schultz @ryantanaka 

As you can see from this PR's commit log, something went terribly wrong. When you initiate a PR in the future, before clicking submit, have a look on the "diff" between the ERDL branch and your branch. You can avoid submitting a PR that will be incorrect, and avoid leaving invalid PRs on ERDL, since we can't delete it. 

Ask Ryan for help if you are stuck, probably easier than me remote. If doesn't work, let me know.

**Comment by matthew-schultz** [comment]
@carlosparadis, I was able to talk with @ryantanaka today about the pull request. 

From what I understand, I think I caused confusion with my method of using commits to save small edits and my inconsistency with commit messages (missing issue numbers or using the previous issue #37 instead of the current issue #47). This pull request should have merged my code into master as I intended, but the large number of my commits with changes to only a few lines of code make following my changes more complicated than it has to be.

Regarding the commit messages with issue numbers from the previous branch #37, there was some local code from my #37 branch (mostly implementing egauge api tests) that I hadn't pushed to github that I ended up building on in #47.

I will be working on revising the commit messages within my branch, so that they have the current issue number, and combining related commits for clarity, if that sounds good to you. 

I should be able to avoid this kind of issue in future pull requests by organizing my commits into features once I get code working and messaging you more often about my progress in the future.

How does that sound to you?

**Comment by matthew-schultz** [comment]
@carlosparadis 

Do you think it would be better for my commits to be something more simple like this:
- remove empty egauge data collection script
- remove egauge api test shell script
- update egauge api to read and write timestamps to file
- build TestEgaugeAPI class

or more incremental than that (maybe 10-15 commits)?

**Comment by carlosparadis** [comment]
@matthew-schultz 

> remove empty egauge data collection script
> remove egauge api test shell script

What is this empty egauge data collection / test shell? Doesn't ring a bell 2 items above.

> update egauge api to read and write timestamps to file

Is this the "last timestamp only" or the timestamp log that will go in the database?

> build TestEgaugeAPI class

What is this about?

**Comment by matthew-schultz** [comment]
@carlosparadis

How do these updated commit messages sound?
- remove bash script used for testing egauge_api.py
- remove partially-built python script that would have been used to call multiple egauge sensors
- update egauge_api to read timestamp from file (representing the last time egauge_api was run successfully) and then append last timestamp to file after successfully obtaining at least one row of readings from the given egauge sensor
- build TestEgaugeAPI class to test egauge_api.py by making a large egauge_api call and a set of smaller egauge_api calls over the same amount of time and comparing the two sets output data to confirm they match

> remove egauge api test shell script

I used to have a bash script I would run that would call egauge_api.py with specific values for testing. But I eventually replaced it by using python default arguments in egauge_api for some testing and using a full-fledged test class 'TestEgaugeAPI' that I wrote.

> remove empty egauge data collection script

I was considering splitting egauge_api.py into a script that would deal with scheduling api requests to multiple sensors and another script that would make the actual egauge_api request, so I started building a scheduling script. 
I think I was getting a little ahead of myself; also, crontab should be able to deal with most of the scheduling, so I removed the script.

>> update egauge api to read and write timestamps to file

> Is this the "last timestamp only" or the timestamp log that will go in the database?

Right now, it just appends the current time (in timestamp form) to a file after successfully obtaining at least one row of data from the given egauge sensor. I was also assuming that would be the same timestamp that would eventually be inserted into the database.

> build TestEgaugeAPI class

I remember previously talking with you about thoroughly testing the results of the egauge_api request to make sure there were no duplicate values. I thought it would be beneficial to separate that test code into its own python class, to avoid cluttering the code in egauge_api.py.

The test class has a function that first makes one api call over a large amount of time and writes the data to a csv representing the 'expected output'. It then makes multiple smaller calls that each append the data to a 'test output' csv file and add up to cover the same amount of time. It then compares the 'expected output' and 'test output' csv files for any differences and will output a failure message if they do not match.

**Comment by carlosparadis** [comment]
@matthew-schultz Let's iterate this via the PR for the time being, I think this will be good reference for the near future and for others too on how we went about deciding this and why. If we get too stuck we can for sure try a call.

> I used to have a bash script I would run that would call egauge_api.py with specific values for testing. But I eventually replaced it with the class TestEgaugeAPI.

If you are going as far as creating a class for Tests, why not use a Unit Test framework? 

> I ended up not using this script, so I removed it.

If the file never came into existence, then no need for the commit! It will prompt someone to wonder what was the file about (like I just did) without need from what you are saying.

> Right now, it just appends the current time (in timestamp form) to a file after successfully obtaining at least one row of data from the given egauge sensor. I was also assuming that would be the same timestamp that would eventually be inserted into the database.

How about them rewording:

`"update egauge_api to read timestamp from file" ` to `update egauge_api to read single timestamp from file` so we remember this is not the log of all of them?

Let me know if I missed anything!

**Comment by matthew-schultz** [comment]
@carlosparadis

Yeah, I can see the value in having the iteration process recorded here. Sometimes it just takes me a while to write responses to your questions haha.

--

>> I used to have a bash script I would run that would call egauge_api.py with specific values for testing. But I eventually replaced it with the class TestEgaugeAPI.

> If you are going as far as creating a class for Tests, why not use a Unit Test framework?

Ahh, I could have been clearer. The TestEgaugeAPI class uses the Python unittest module.

### commit message: "remove bash script used for testing egauge_api.py"

--

>> I ended up not using this script, so I removed it.

> If the file never came into existence, then no need for the commit! It will prompt someone to wonder what was the file about (like I just did) without need from what you are saying.

Sorry, I think I need to clarify again, the file was committed in the previous pull request, but is no longer used and has been removed as of this pull request.

Do you think it should still have its own commit message like this?

### commit message: "remove unnecessary python script that called egauge_api.py"

--

> How about them rewording:
>
> "update egauge_api to read timestamp from file" to update egauge_api to read single timestamp from file so we remember this is not the log of all of them?

I just want to make sure we both understand each other:

1. one of the files egauge_api writes to is just a list of timestamps
2. every time it runs, it reads through that file until it gets to the last timestamp
3. after a successful api request with >=1 rows of sensor data, it adds the current time to the end of that file
4. I call that file 'timestamp.log' by default because '.log' files are .gitignored in the repo
5. I have a file named 'ouput.log' by default, where I write any egauge sensor data obtained, as csv rows.
6. I also have an file hardcoded as 'error.log' where any thrown exception are written, along with the current time.

Do you think my use of naming files '.log' could cause confusion in the future? I could update the gitignore with a new type of file extension (like '.dev').

### commit message: "update egauge_api to read single timestamp from file and append last timestamp to file after successfully obtaining at least one row of readings from the given egauge sensor"

--
Does this commit message sound alright to you for the [TestEgauageAPI class](https://github.com/matthew-schultz/sensors/blob/47-egauge-timestamps/egauge/script/test_egauge_api.py) ?

### commit message: "build TestEgaugeAPI class inheriting from python unittest module"

**Comment by carlosparadis** [comment]
:^) You see how big the text of these messages are given the number of commits in this PR, in the future it may be easier to check earlier by sending a smaller PR. 

If my understanding is correct your class is for the unittest, and that replaces a handmade script to run tests, I would just make one commit, as they are of the same intent such as:

 * Replace test script by unittest class

> Do you think my use of naming files '.log' could cause confusion in the future? I could update the gitignore with a new type of file extension (like '.dev').

 I wouldn't bother. This is just an intermediate exercise. We will be storing all this in the database and **never** on files on the server. This makes it much easier for Eileen and others who don't "surf the server" to inspect if there are any problems, and is one of the biggest bottlenecks for scrape-utils.

Also,

> commit message: "update egauge_api to read single timestamp from file and append last timestamp to file after successfully obtaining at least one row of readings from the given egauge sensor"
 
Commit messages have a very small number of characters, this is too big. You are welcomed to put any amount of text on the body of the commit, though by using "git commit" instead of git commit -m.

**Comment by matthew-schultz** [comment]
@carlosparadis 

Yeah, I think I'll take you up by splitting up large issues into smaller pull requests in the future haha. For some reason, I was thinking I would only do one pull request for all of issue #47 (^_^''')

> If my understanding is correct your class is for the unittest, and that replaces a handmade script to run tests. I would just make one commit, as they are of the same intent such as: "Replace test script by unittest class"

Okay, I'll make the replacement of my handmade script with my unittest class one of the commits.

> We will be storing all this in the database and never on files on the server. This makes it much easier for Eileen and others who don't "surf the server" to inspect if there are any problems, and is one of the biggest bottlenecks for scrape-utils.

Got it, that makes sense that we would want to insert logged data into the database instead of trying to go through log files.

Have you ever had any major issues with connecting to or inserting data into the database? I was thinking it might be good to still have one error log file on the server to refer to in case something fails like the database connection.

> Commit messages have a very small number of characters, this is too big. You are welcome to put any amount of text on the body of the commit, though by using "git commit" instead of git commit -m.

Ahh, thank you for reminding me about that option for the longer explanations.

I should be able to send you an updated list of commits by the end of day Friday

Thank you for taking the time to respond multiple times today! : D
I think I'm starting to get a better feel for the pull request and revision cycle now.

**Comment by matthew-schultz** [comment]
@carlosparadis how does it sound if I update the pull request to consist of these three commits?

- Remove unnecessary python script that called egauge_api.py
- Update egauge_api to read single timestamp from file
- Replace test script with unittest class

**Comment by carlosparadis** [comment]
@matthew-schultz I am still confused about the meaning of this commit:

 * Remove unnecessary python script that called egauge_api.py

**Comment by matthew-schultz** [comment]
@carlosparadis Sorry for the late response; I requested off from work on Monday for an event.

This is the python script that I found unnecessary and removed:

https://github.com/erdl/sensors/blob/fb5a98448eb8796db84523621643964a48f68759/egauge/script/run_egauge_data_collection.py#L1-L8

I [committed run_egauge_data_collection.py](https://github.com/erdl/sensors/commit/73f64be4aeef441aa5103886aac5f9e9d4116478) as part of my previous pull request #44 thinking it might be useful to separate some features from egauge_api.py (like making a call to egauge_api for each sensor) into their own file.

However, later in the development process, creating a separate script just to make multiple calls to egauge_api felt unnecessary, so I added a commit removing the file run_egauge_data_collection.py

**Comment by carlosparadis** [comment]
@matthew-schultz 

Alright, sure you can mention removing this file and keep it as one as well. I don't know how I let this second file slip in though. I guess I am getting senile.

Here is a shot on the commit name based on what you told me of the intent of this commit was:

 * Remove unnecessary function call dependencies to collect egauge data (I renamed this)
 * Update egauge_api to read single timestamp from file
 * Replace test script with unittest class

Usually mentioning things like:

 * Code language 
 * file name
 * any other information git will already tell you 

On the commit label is redundant (use the words instead for the "why"). It is ok to mention on the body of the commit though. You want to log in the commit label especially those things I cant easily tell by doing a `git diff`. In this case:

> Remove unnecessary python script that called egauge_api.py

Using a diff on your commit, I will know you are 1) deleting the egauge_api.py file, and that 2) the language is python. However, I would not know why you deem **unnecessary**, which is why I mentioned was the function calls (since we agreed to abide by the KISS principle for the scripts for the time being). 

## Side Note

I am a bit worried about the timeline, since by the end of the summer the hopes and dreams are that the issue MATT would be done (this would be the egauge tasks done, and the other main sensors like HOBO, and webctrl) all running in the server.

This is partially my fault snowballing the responses with all that is going on here, but I would like to see how realistic it is for us to set some dedicated issues and wrap this effort by the time Eileen comes back.

The semester is always the complicated part, so wrapping the details during the summer is likely at the best of our interest.

Let me know your thoughts. Also, @ryantanaka is probably the best person to help you with the commits fixing. There is already so many in this PR I dont even know if a squash is a good idea anymore.

**Comment by carlosparadis** [comment]
@matthew-schultz Sure! On the working hours, just run that with Eileen today and what you are doing to see if she is fine. :) 

Less unit tests are ok. While I appreciate even going as far as TDD, given our specs are still somewhat foggy, I think it is best to delay on that. Check with me on libraries instead of spending time digging on them. Most of the libraries necessary to do this already live somewhere in ERDL. For instance, we already use an ORM library in the Survey Admin project, which you could use it as example code for reference. 

I am going to go ahead and close this PR. Let's continue this on the MATT issue as you suggested.

**Comment by matthew-schultz** [comment]
@carlosparadis I'm not sure if github sent you a notification or not, so just letting you know that I've pushed the updated commits for #47
: D

**Pull request merged**
